library(checkmate)
library(dplyr)
library(lockr)
library(testthat)

test_check("lockr")

# # For development use only (comment the code after use (Ctrl + Shift + C)).
#
# cffr::cff_write()
# codemetar::write_codemeta()
# covr::package_coverage()
# devtools::check()
# devtools::document()
# devtools::install()
# devtools::release()
# devtools:test()
# goodpractice::gp()
# lintr::lint_package()
# pkgdown::build_article("x")
# pkgdown::build_favicons(overwrite = TRUE)
# pkgdown::build_reference()
# pkgdown::build_site()
# rutils::update_pkg_versions()
# spelling::spell_check_package()
# spelling::update_wordlist()
# tcltk::tk_choose.files()
# urlchecker::url_check()
# usethis::use_coverage()
# usethis::use_dev_version()
# usethis::use_dev_version()
# usethis::use_github_action("check-standard")
# usethis::use_logo(tcltk::tk_choose.files())
# usethis::use_release_issue("#.#.#")
# usethis::use_tidy_description()
# usethis::use_version()

# # Encryption
#
# lockr::rsa_keygen()
# lockr::lock_dir(dir = "./inst/extdata")
# lockr::unlock_dir(dir = "./inst/extdata")
# lockr::lock_file(file.choose())
# lockr::unlock_file(file.choose())
